In [2]:
import pandas as pd
import numpy as np

In [11]:
data = pd.read_csv('Private_Schools.csv')

In [12]:
data.head()

,X,Y,FID,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,...,SOURCEDATE,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,START_GRAD,END_GRADE,FT_TEACHER,SHELTER_ID
0,-8.136078e+06,5.055506e+06,1,1201,A0507274,A CHILD'S GARDEN,20 IVY BROOK RD,SHELTON,CT,6484,...,2010/01/29 00:00:00,IMAGERY,2010/02/25 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,1,6,2,3,2,NOT AVAILABLE
1,-8.147300e+06,5.037067e+06,2,1202,A0500844,BRIDGEPORT INTERNATIONAL ACADEMY,285 LAFAYETTE ST STE 200,BRIDGEPORT,CT,6604,...,2010/01/29 00:00:00,IMAGERY/OTHER,2010/02/23 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2,60,14,17,8,NOT AVAILABLE
2,-8.197042e+06,5.018050e+06,3,1203,A0108054,CARMEL ACADMEY,270 LAKE AVE,GREENWICH,CT,6830,...,2010/01/29 00:00:00,IMAGERY,2010/03/05 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,1,225,3,13,53,NOT AVAILABLE
3,-8.171504e+06,5.077291e+06,4,1204,A0507283,COUNTRY KIDS CLUB,94 OLD STATE RD,BROOKFIELD,CT,6804,...,2010/01/29 00:00:00,GEOCODE,2010/02/25 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,1,10,2,3,1,NOT AVAILABLE
4,-8.197596e+06,5.017131e+06,5,1205,01612613,EAGLE HILL SCHOOL,45 GLENVILLE RD,GREENWICH,CT,6831,...,2010/01/29 00:00:00,IMAGERY/OTHER,2010/02/26 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,3,253,4,15,65,NOT AVAILABLE

In [13]:
data = data.drop(
    labels=["FID","OBJECTID", "NCESID", "STATE", "SOURCEDATE", "VAL_DATE", "WEBSITE", 
    "LEVEL_", "ENROLLMENT", "START_GRAD", "END_GRADE", "FT_TEACHER", "SHELTER_ID"], 
    axis=1)

In [20]:
data.head()

,X,Y,NAME,ADDRESS,CITY,ZIP,ZIP4,TELEPHONE,TYPE,STATUS,POPULATION,COUNTY,COUNTYFIPS,COUNTRY,LATITUDE,LONGITUDE,NAICS_CODE,NAICS_DESC,SOURCE,VAL_METHOD
0,-8.136078e+06,5.055506e+06,A CHILD'S GARDEN,20 IVY BROOK RD,SHELTON,6484,6418,NOT AVAILABLE,7,1,8,FAIRFIELD,9001,USA,41.291990,-73.087632,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,IMAGERY
1,-8.147300e+06,5.037067e+06,BRIDGEPORT INTERNATIONAL ACADEMY,285 LAFAYETTE ST STE 200,BRIDGEPORT,6604,5755,NOT AVAILABLE,3,1,68,FAIRFIELD,9001,USA,41.167416,-73.188438,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,IMAGERY/OTHER
2,-8.197042e+06,5.018050e+06,CARMEL ACADMEY,270 LAKE AVE,GREENWICH,6830,4518,NOT AVAILABLE,3,1,278,FAIRFIELD,9001,USA,41.038690,-73.635283,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,IMAGERY
3,-8.171504e+06,5.077291e+06,COUNTRY KIDS CLUB,94 OLD STATE RD,BROOKFIELD,6804,2524,NOT AVAILABLE,7,1,11,FAIRFIELD,9001,USA,41.438861,-73.405868,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,GEOCODE
4,-8.197596e+06,5.017131e+06,EAGLE HILL SCHOOL,45 GLENVILLE RD,GREENWICH,6831,NOT AVAILABLE,NOT AVAILABLE,4,1,318,FAIRFIELD,9001,USA,41.032465,-73.640254,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,IMAGERY/OTHER

In [23]:
new_data = pd.DataFrame({
    'NAME': data['NAME'],
    'LATITUDE': data['LATITUDE'],
    'LONGITUDE': data['LONGITUDE']
    })

In [27]:
new_data.shape

(31064, 3)

In [29]:
new_data.to_csv('privateSchool.csv', sep='\t', encoding='utf-8')